### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by cyr3ne** [mkotajny/CA4_TeaCozy#1]
https://github.com/mkotajny/CA4_TeaCozy/blob/8ed67d4221ddf061d98f0a0bb1a25563fb387948/index.html#L89

Maybe you can try adding the copyright sign in the future :)

**Comment by NoHaxz2Win** [comment]
Added the copyright logo, and centered the footer just because it looks more professional :)

[CA4_TeaCozy-master.zip](https://github.com/mkotajny/CA4_TeaCozy/files/1565299/CA4_TeaCozy-master.zip)
